version: '3.8'

services:
  mongo:
    image: mongo
    container_name: beauty-mongo
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

