app = 'succarbanat'
primary_region = 'cdg'

[build]

[env]
SPRING_DATA_MONGODB_URI = "mongodb+srv://admin:BeautyCenterAdmin@beauty-center.ru5fy7s.mongodb.net/beauty-center-prod?retryWrites=true&w=majority&appName=beauty-center"
SPRING_PROFILES_ACTIVE = "prod"
CORS_ALLOWED_ORIGINS = "https://your-frontend-domain.com"
FILE_UPLOAD_BASE_URL = "https://your-app-name.onrender.com/api/files"
LOG_LEVEL = "INFO"
JSON_PRETTY_PRINT = "false"
THYMELEAF_CACHE = "true"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
